/*
  Copyright (c) 2025 Maciej Miklas
  Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
*/
;----------------------------------------------------------;
;                   Following Enemy                        ;
;----------------------------------------------------------;
    MODULE fed
    ; ### TO USE THIS MODULE: CALL dbs.SetupFollowingEnemyBank ###

; Sprites, used by single enemies (#spriteExXX).
fEnemySprites
    SPR {089/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy01/*EXT_DATA_POINTER*/}
    SPR {099/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy02/*EXT_DATA_POINTER*/}
    SPR {100/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy03/*EXT_DATA_POINTER*/}
    SPR {101/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy04/*EXT_DATA_POINTER*/}
    SPR {102/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy05/*EXT_DATA_POINTER*/}
    SPR {103/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy06/*EXT_DATA_POINTER*/}
    SPR {104/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy07/*EXT_DATA_POINTER*/}
    SPR {105/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy08/*EXT_DATA_POINTER*/}
    SPR {106/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy09/*EXT_DATA_POINTER*/}
    SPR {107/*ID*/, sr.SDB_ENEMY1A/*SDB_INIT*/, 0/*SDB_POINTER*/, 0/*X*/, 0/*Y*/, 0/*STATE*/, 0/*NEXT*/, 0/*REMAINING*/, fEnemy10/*EXT_DATA_POINTER*/}
fEnemySize              BYTE 1
FOLLOWING_FENEMY_SIZE   = 10                    ; Max size

fEnemy01
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy02
    FE {STATE_DEPLOY_LEFT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy03
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy04
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy05
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy06
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy07
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy08
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy09
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

fEnemy10
    FE {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 01/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/, 0,0,0,0,0,0}

; ##############################################
; Level 8
fEnemyL08
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 040/*RESPAWN_Y*/, 15/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 040/*RESPAWN_Y*/, 25/*RESPAWN_DELAY*/, 01/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 080/*RESPAWN_Y*/, 15/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 080/*RESPAWN_Y*/, 13/*RESPAWN_DELAY*/, 02/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 120/*RESPAWN_Y*/, 11/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 120/*RESPAWN_Y*/, 20/*RESPAWN_DELAY*/, 02/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 180/*RESPAWN_Y*/, 13/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 180/*RESPAWN_Y*/, 18/*RESPAWN_DELAY*/, 01/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 200/*RESPAWN_Y*/, 25/*RESPAWN_DELAY*/, 02/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 200/*RESPAWN_Y*/, 10/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
FENEMY_SIZE_L8          = 10

; Level 9
fEnemyL09
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 024/*RESPAWN_Y*/, 15/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 024/*RESPAWN_Y*/, 25/*RESPAWN_DELAY*/, 01/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 040/*RESPAWN_Y*/, 15/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 040/*RESPAWN_Y*/, 13/*RESPAWN_DELAY*/, 02/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 100/*RESPAWN_Y*/, 11/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 080/*RESPAWN_Y*/, 20/*RESPAWN_DELAY*/, 02/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 160/*RESPAWN_Y*/, 13/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 180/*RESPAWN_Y*/, 18/*RESPAWN_DELAY*/, 01/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_LEFT  /*STATE*/, 200/*RESPAWN_Y*/, 25/*RESPAWN_DELAY*/, 03/*MOVE_DELAY*/}
    FES {STATE_DEPLOY_RIGHT /*STATE*/, 200/*RESPAWN_Y*/, 10/*RESPAWN_DELAY*/, 00/*MOVE_DELAY*/}
FENEMY_SIZE_L9          = 10

;----------------------------------------------------------;
;                       ENDMODULE                          ;
;----------------------------------------------------------;
    ENDMODULE